/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: {
          page: "hsl(var(--surface-page) / <alpha-value>)",
          card: "hsl(var(--surface-card) / <alpha-value>)",
          muted: "hsl(var(--surface-muted) / <alpha-value>)",
          dark: "hsl(var(--surface-dark) / <alpha-value>)",
          "dark-panel": "hsl(var(--surface-dark-panel) / <alpha-value>)",
        },
        brand: {
          navy: "hsl(var(--brand-navy) / <alpha-value>)",
          "navy-hover": "hsl(var(--brand-navy-hover) / <alpha-value>)",
          copper: "hsl(var(--brand-copper) / <alpha-value>)",
          "copper-deep": "hsl(var(--brand-copper-deep) / <alpha-value>)",
          "copper-tint": "hsl(var(--brand-copper-tint) / <alpha-value>)",
        },
        ink: {
          DEFAULT: "hsl(var(--text-default) / <alpha-value>)",
          muted: "hsl(var(--text-muted) / <alpha-value>)",
          placeholder: "hsl(var(--text-placeholder) / <alpha-value>)",
          "on-dark": "hsl(var(--text-on-dark) / <alpha-value>)",
          "muted-on-dark": "hsl(var(--text-muted-on-dark) / <alpha-value>)",
        },
        border: {
          DEFAULT: "hsl(var(--border-default))",
          input: "hsl(var(--border-input))",
          strong: "hsl(var(--border-strong))",
          "on-dark": "hsl(var(--border-on-dark))",
        },
        status: {
          "success-bg": "hsl(var(--status-success-bg) / <alpha-value>)",
          "success-fg": "hsl(var(--status-success-fg) / <alpha-value>)",
          "success-br": "hsl(var(--status-success-br) / <alpha-value>)",
          "warning-bg": "hsl(var(--status-warning-bg) / <alpha-value>)",
          "warning-fg": "hsl(var(--status-warning-fg) / <alpha-value>)",
          "warning-br": "hsl(var(--status-warning-br) / <alpha-value>)",
          "error-bg": "hsl(var(--status-error-bg) / <alpha-value>)",
          "error-fg": "hsl(var(--status-error-fg) / <alpha-value>)",
          "error-br": "hsl(var(--status-error-br) / <alpha-value>)",
          "info-bg": "hsl(var(--status-info-bg) / <alpha-value>)",
          "info-fg": "hsl(var(--status-info-fg) / <alpha-value>)",
          "info-br": "hsl(var(--status-info-br) / <alpha-value>)",
        },
        viz: {
          0: "hsl(var(--viz-0) / <alpha-value>)",
          1: "hsl(var(--viz-1) / <alpha-value>)",
          2: "hsl(var(--viz-2) / <alpha-value>)",
          3: "hsl(var(--viz-3) / <alpha-value>)",
          4: "hsl(var(--viz-4) / <alpha-value>)",
          5: "hsl(var(--viz-5) / <alpha-value>)",
          6: "hsl(var(--viz-6) / <alpha-value>)",
          7: "hsl(var(--viz-7) / <alpha-value>)",
        },
      },
      fontFamily: {
        display: ['"Cormorant Garamond"', "Cormorant", "Garamond", "serif"],
        editorial: ['"EB Garamond"', "Garamond", "Georgia", "serif"],
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        mono: ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "monospace"],
      },
      fontSize: {
        "display-xl": ["clamp(3.5rem, 6vw, 5.5rem)", { lineHeight: "1.05", letterSpacing: "-0.02em" }],
        "display-lg": ["clamp(2.75rem, 4.5vw, 4rem)", { lineHeight: "1.1", letterSpacing: "-0.015em" }],
        "display-md": ["clamp(2.25rem, 3.5vw, 3rem)", { lineHeight: "1.15", letterSpacing: "-0.01em" }],
        "display-sm": ["1.75rem", { lineHeight: "1.2" }],
        "eyebrow": ["0.8125rem", { lineHeight: "1.3", letterSpacing: "0.14em" }],
      },
      maxWidth: {
        "screen-narrow": "720px",
        "screen-prose": "960px",
        "screen-default": "1200px",
        "screen-wide": "1440px",
      },
      letterSpacing: {
        tightest: "-0.025em",
        eyebrow: "0.14em",
      },
      boxShadow: {
        input: "0 1px 1px 0 rgba(15, 23, 42, 0.04)",
        elevated: "0 8px 24px -8px rgba(15, 23, 42, 0.18)",
        "card-soft": "0 1px 2px 0 rgba(15, 23, 42, 0.03), 0 0 0 1px hsl(var(--border-default))",
      },
      transitionDuration: {
        fast: "150ms",
        DEFAULT: "250ms",
        slow: "400ms",
      },
      transitionTimingFunction: {
        DEFAULT: "cubic-bezier(0.22, 0.61, 0.36, 1)",
      },
      borderRadius: {
        DEFAULT: "4px",
        sm: "2px",
        md: "6px",
        lg: "8px",
      },
      typography: () => ({
        editorial: {
          css: {
            "--tw-prose-body": "hsl(var(--text-default))",
            "--tw-prose-headings": "hsl(var(--text-default))",
            "--tw-prose-links": "hsl(var(--brand-navy))",
            "--tw-prose-bold": "hsl(var(--text-default))",
            "--tw-prose-quotes": "hsl(var(--text-default))",
            "--tw-prose-quote-borders": "hsl(var(--brand-copper))",
            "--tw-prose-captions": "hsl(var(--text-muted))",
            "--tw-prose-counters": "hsl(var(--text-muted))",
            "--tw-prose-bullets": "hsl(var(--text-muted))",
            "--tw-prose-hr": "hsl(var(--border-default))",
            fontFamily: '"EB Garamond", Garamond, Georgia, serif',
            fontSize: "1.125rem",
            lineHeight: "1.65",
            fontFeatureSettings: '"onum" 1, "kern" 1, "liga" 1',
            h1: { fontFamily: '"Cormorant Garamond", serif', fontWeight: "500" },
            h2: { fontFamily: '"Cormorant Garamond", serif', fontWeight: "500" },
            h3: { fontFamily: "Inter, sans-serif", fontWeight: "600", fontSize: "1.25rem" },
            h4: { fontFamily: "Inter, sans-serif", fontWeight: "600", fontSize: "1.0625rem" },
            a: { textUnderlineOffset: "3px", textDecorationThickness: "1px" },
          },
        },
      }),
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
